<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-us" lang="en-us">
<head>
  <link href="//gmpg.org/xfn/11" rel="profile">
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="Hugo 0.59.0-DEV" />

  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title> &middot; Jay Blog</title>

  
  <link type="text/css" rel="stylesheet" href="http://blog.jaytogo.com/css/print.css" media="print">
  <link type="text/css" rel="stylesheet" href="http://blog.jaytogo.com/css/poole.css">
  <link type="text/css" rel="stylesheet" href="http://blog.jaytogo.com/css/syntax.css">
  <link type="text/css" rel="stylesheet" href="http://blog.jaytogo.com/css/hyde.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface|PT+Sans:400,400i,700">


  
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
  <link rel="shortcut icon" href="/favicon.png">

  
  
</head>

  <body class=" ">
  <aside class="sidebar">
  <div class="container sidebar-sticky">
    <div class="sidebar-about">
      <a href="http://blog.jaytogo.com/"><h1>Jay Blog</h1></a>
      <p class="lead">
       learning rust, reviwe c, erp, javascript, blog, python 
      </p>
    </div>

    <nav>
      <ul class="sidebar-nav">
        <li><a href="http://blog.jaytogo.com/">Home</a> </li>
        <li><a href="/rust/"> rust </a></li>
      </ul>
    </nav>

    <p>&copy; 2019. All rights reserved. </p>
  </div>
</aside>

    <main class="content container">
    <div class="post">
  <h1></h1>
  <time datetime=0001-01-01T00:00:00Z class="post-date">Mon, Jan 1, 0001</time>
  

<h1 id="error-handling-in-rust">Error Handling in Rust</h1>

<p>From: <a href="https://blog.burntsushi.net/rust-error-handling/">rust-error-handling</a></p>

<p>May 14, 2015</p>

<p>Like most programming languages, Rust encourages the programmer to handle errors in a particular way. Generally speaking, error handling is divided into two broad categories: exceptions and return values. Rust opts for return values.</p>

<p>In this article, I intend to provide a comprehensive treatment of how to deal with errors in Rust. More than that, I will attempt to introduce error handling one piece at a time so that you’ll come away with a solid working knowledge of how everything fits together.</p>

<p>When done naively, error handling in Rust can be verbose and annoying. This article will explore those stumbling blocks and demonstrate how to use the standard library to make error handling concise and ergonomic.</p>

<p><strong>Target audience</strong>: Those new to Rust that don’t know its error handling idioms yet. Some familiarity with Rust is helpful. (This article makes heavy use of some standard traits and some very light use of closures and macros.)</p>

<p><strong>Update (2018/04/14)</strong>: Examples were converted to  <code>?</code>, and some text was added to give historical context on the change.</p>

<h2 id="brief-notes">Brief notes</h2>

<p>All code samples in this post compile with Rust  <code>1.0.0-beta.5</code>. They should continue to work as Rust 1.0 stable is released.</p>

<p>All code can be found and compiled in  <a href="https://github.com/BurntSushi/blog/tree/master/code/rust-error-handling">my blog’s repository</a>.</p>

<p>The  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/">Rust Book</a>  has a  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/error-handling.html">section on error handling</a>. It gives a very brief overview, but doesn’t (yet) go into enough detail, particularly when working with some of the more recent additions to the standard library.</p>

<h2 id="run-the-code">Run the code!</h2>

<p>If you’d like to run any of the code samples below, then the following should work:</p>

<pre><code class="language-sh">$ git clone git://github.com/BurntSushi/blog
$ cd blog/code/rust-error-handling
$ cargo run --bin NAME-OF-CODE-SAMPLE [ args ... ]
</code></pre>

<p>Each code sample is labeled with its name. (Code samples without a name aren’t available to be run this way. Sorry.)</p>

<h2 id="table-of-contents">Table of Contents</h2>

<p>This article is very long, mostly because I start at the very beginning with sum types and combinators, and try to motivate the way Rust does error handling incrementally. As such, programmers with experience in other expressive type systems may want to jump around. Here’s my very brief guide:</p>

<ul>
<li>If you’re new to Rust, systems programming and expressive type systems, then start at the beginning and work your way through. (If you’re brand new, you should probably read through the  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/">Rust book</a>  first.)</li>
<li>If you’ve never seen Rust before but have experience with functional languages (“algebraic data types” and “combinators” make you feel warm and fuzzy), then you can probably skip right over the basics and start by skimming  <a href="https://blog.burntsushi.net/rust-error-handling/#working-with-multiple-error-types">multiple error types</a>, and work you’re way into a full read of<a href="https://blog.burntsushi.net/rust-error-handling/#standard-library-traits-used-for-error-handling">standard library error traits</a>. (Skimming  <a href="https://blog.burntsushi.net/rust-error-handling/#the-basics">the basics</a>  might be a good idea to just get a feel for the syntax if you’ve really never seen Rust before.) You may need to  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/">consult the Rust book</a>  for help with Rust closures and macros.</li>
<li>If you’re already experienced with Rust and just want the skinny on error handling, then you can probably skip straight  <a href="https://blog.burntsushi.net/rust-error-handling/#the-short-story">to the end</a>. You may find it useful to skim the  <a href="https://blog.burntsushi.net/rust-error-handling/#case-study-a-program-to-read-population-data">case study</a>  for examples.</li>
</ul>

<hr />

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-basics">The Basics</a>

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#unwrapping-explained">Unwrapping explained</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-option-type">The  <code>Option</code>  type</a>

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#composing-option-t-values">Composing  <code>Option&lt;T&gt;</code>  values</a></li>
</ul></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-result-type">The  <code>Result</code>  type</a>

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#parsing-integers">Parsing integers</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-result-type-alias-idiom">The  <code>Result</code>  type alias idiom</a></li>
</ul></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#a-brief-interlude-unwrapping-isn-t-evil">A brief interlude: unwrapping isn’t evil</a></li>
</ul></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#working-with-multiple-error-types">Working with multiple error types</a>

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#composing-option-and-result">Composing  <code>Option</code>  and  <code>Result</code></a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-limits-of-combinators">The limits of combinators</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#early-returns">Early returns</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-try-macro-operator">The  <code>try!</code>  macro/<code>?</code>  operator</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#defining-your-own-error-type">Defining your own error type</a></li>
</ul></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#standard-library-traits-used-for-error-handling">Standard library traits used for error handling</a>

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-error-trait">The  <code>Error</code>  trait</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-from-trait">The  <code>From</code>  trait</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-real-try-macro-operator">The real  <code>try!</code>  macro/<code>?</code>  operator</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#composing-custom-error-types">Composing custom error types</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#advice-for-library-writers">Advice for library writers</a></li>
</ul></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#case-study-a-program-to-read-population-data">Case study: A program to read population data</a>

<ul>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#it-s-on-github">It’s on Github</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#initial-setup">Initial setup</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#argument-parsing">Argument parsing</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#writing-the-logic">Writing the logic</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#error-handling-with-box-error">Error handling with  <code>Box&lt;Error&gt;</code></a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#reading-from-stdin">Reading from stdin</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#error-handling-with-a-custom-type">Error handling with a custom type</a></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#adding-functionality">Adding functionality</a></li>
</ul></li>
<li><a href="https://blog.burntsushi.net/rust-error-handling/#the-short-story">The short story</a></li>
</ul>

<h2 id="the-basics">The Basics</h2>

<p>I like to think of error handling as using  <em>case analysis</em>  to determine whether a computation was successful or not. As we will see, the key to ergonomic error handling is reducing the amount of explicit case analysis the programmer has to do while keeping code composable.</p>

<p>Keeping code composable is important, because without that requirement, we could  <a href="http://doc.rust-lang.org/std/macro.panic!.html"><code>panic</code></a>  whenever we come across something unexpected. (<code>panic</code>  causes the current task to unwind, and in most cases, the entire program aborts.) Here’s an example:</p>

<p>panic-simple</p>

<pre><code class="language-rust">// Guess a number between 1 and 10.
// If it matches the number I had in mind, return true. Else, return false.
fn guess(n: i32) -&gt; bool {
    if n &lt; 1 || n &gt; 10 {
        panic!(&quot;Invalid number: {}&quot;, n);
    }
    n == 5
}

fn main() {
    guess(11);
}

</code></pre>

<p>(If you like, it’s easy to  <a href="https://blog.burntsushi.net/rust-error-handling/#run-the-code">run this code</a>.)</p>

<p>If you try running this code, the program will crash with a message like this:</p>

<pre><code class="language-sh">thread '&lt;main&gt;' panicked at 'Invalid number: 11', src/bin/panic-simple.rs:5
</code></pre>

<p>Here’s another example that is slightly less contrived. A program that accepts an integer as an argument, doubles it and prints it.</p>

<p>unwrap-double</p>

<pre><code class="language-rust">use std::env;

fn main() {
    let mut argv = env::args();
    let arg: String = argv.nth(1).unwrap(); // error 1
    let n: i32 = arg.parse().unwrap(); // error 2
    println!(&quot;{}&quot;, 2 * n);
}

// $ cargo run --bin unwrap-double 5
// 10

</code></pre>

<p>If you give this program zero arguments (error 1) or if the first argument isn’t an integer (error 2), the program will panic just like in the first example.</p>

<p>I like to think of this style of error handling as similar to a bull running through a china shop. The bull will get to where it wants to go, but it will trample everything in the process.</p>

<h3 id="unwrapping-explained">Unwrapping explained</h3>

<p>In the previous example (<a href="https://blog.burntsushi.net/rust-error-handling/#code-unwrap-double"><code>unwrap-double</code></a>), I claimed that the program would simply panic if it reached one of the two error conditions, yet, the program does not include an explicit call to  <code>panic</code>  like the first example (<a href="https://blog.burntsushi.net/rust-error-handling/#code-panic-simple"><code>panic-simple</code></a>). This is because the panic is embedded in the calls to  <code>unwrap</code>.</p>

<p>To “unwrap” something in Rust is to say, “Give me the result of the computation, and if there was an error, just panic and stop the program.” It would be better if I just showed the code for unwrapping because it is so simple, but to do that, we will first need to explore the  <code>Option</code>  and  <code>Result</code>  types. Both of these types have a method called  <code>unwrap</code>  defined on them.</p>

<h3 id="the-option-type">The  <code>Option</code>  type</h3>

<p>The  <code>Option</code>  type is  <a href="http://doc.rust-lang.org/std/option/enum.Option.html">defined in the standard library</a>:</p>

<p>option-def</p>

<pre><code class="language-rust">enum Option&lt;T&gt; {
    None,
    Some(T),
}

</code></pre>

<p>The  <code>Option</code>  type is a way to use Rust’s type system to express the  <em>possibility of absence</em>. Encoding the possibility of absence into the type system is an important concept because it will cause the compiler to force the programmer to handle that absence. Let’s take a look at an example that tries to find a character in a string:</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">// Searches `haystack` for the Unicode character `needle`. If one is found, the
// byte offset of the character is returned. Otherwise, `None` is returned.
fn find(haystack: &amp;str, needle: char) -&gt; Option&lt;usize&gt; {
    for (offset, c) in haystack.char_indices() {
        if c == needle {
            return Some(offset);
        }
    }
    None
}

</code></pre>

<p>(Pro-tip: don’t use this code. Instead, use the  <a href="http://doc.rust-lang.org/std/primitive.str.html#method.find"><code>find</code></a>  method from the standard library.)</p>

<p>Notice that when this function finds a matching character, it doesn’t just return the  <code>offset</code>. Instead, it returns  <code>Some(offset)</code>.  <code>Some</code>  is a variant or a  <em>value constructor</em>  for the  <code>Option</code>  type. You can think of it as a function with the type  <code>fn&lt;T&gt;(value: T) -&gt; Option&lt;T&gt;</code>. Correspondingly,  <code>None</code>  is also a value constructor, except it has no arguments. You can think of  <code>None</code>  as a function with the type  <code>fn&lt;T&gt;() -&gt; Option&lt;T&gt;</code>.</p>

<p>This might seem like much ado about nothing, but this is only half of the story. The other half is  _using_the  <code>find</code>  function we’ve written. Let’s try to use it to find the extension in a file name.</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">fn main_find() {
    let file_name = &quot;foobar.rs&quot;;
    match find(file_name, '.') {
        None =&gt; println!(&quot;No file extension found.&quot;),
        Some(i) =&gt; println!(&quot;File extension: {}&quot;, &amp;file_name[i+1..]),
    }
}

</code></pre>

<p>This code uses  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/patterns.html">pattern matching</a>  to do  <em>case analysis</em>  on the  <code>Option&lt;usize&gt;</code>  returned by the  <code>find</code>  function. In fact, case analysis is the only way to get at the value stored inside an  <code>Option&lt;T&gt;</code>. This means that you, as the programmer, must handle the case when an  <code>Option&lt;T&gt;</code>  is  <code>None</code>  instead of  <code>Some(t)</code>.</p>

<p>But wait, what about  <code>unwrap</code>  used in  <a href="https://blog.burntsushi.net/rust-error-handling/#code-unwrap-double"><code>unwrap-double</code></a>? There was no case analysis there! Instead, the case analysis was put inside the  <code>unwrap</code>  method for you. You could define it yourself if you want:</p>

<p>option-def-unwrap</p>

<pre><code class="language-rust">enum Option&lt;T&gt; {
    None,
    Some(T),
}

impl&lt;T&gt; Option&lt;T&gt; {
    fn unwrap(self) -&gt; T {
        match self {
            Option::Some(val) =&gt; val,
            Option::None =&gt;
              panic!(&quot;called `Option::unwrap()` on a `None` value&quot;),
        }
    }
}

</code></pre>

<p>The  <code>unwrap</code>  method  <em>abstracts away the case analysis</em>. This is precisely the thing that makes  <code>unwrap</code>ergonomic to use. Unfortunately, that  <code>panic!</code>  means that  <code>unwrap</code>  is not composable: it is the bull in the china shop.</p>

<h4 id="composing-option-t-values">Composing  <code>Option&lt;T&gt;</code>  values</h4>

<p>In  <a href="https://blog.burntsushi.net/rust-error-handling/#code-option-ex-string-find-2"><code>option-ex-string-find</code></a>  we saw how to use  <code>find</code>  to discover the extension in a file name. Of course, not all file names have a  <code>.</code>  in them, so it’s possible that the file name has no extension. This  <em>possibility of absence</em>  is encoded into the types using  <code>Option&lt;T&gt;</code>. In other words, the compiler will force us to address the possibility that an extension does not exist. In our case, we just print out a message saying as such.</p>

<p>Getting the extension of a file name is a pretty common operation, so it makes sense to put it into a function:</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">// Returns the extension of the given file name, where the extension is defined
// as all characters succeeding the first `.`.
// If `file_name` has no `.`, then `None` is returned.
fn extension_explicit(file_name: &amp;str) -&gt; Option&lt;&amp;str&gt; {
    match find(file_name, '.') {
        None =&gt; None,
        Some(i) =&gt; Some(&amp;file_name[i+1..]),
    }
}

</code></pre>

<p>(Pro-tip: don’t use this code. Use the  <a href="http://doc.rust-lang.org/std/path/struct.Path.html#method.extension"><code>extension</code></a>  method in the standard library instead.)</p>

<p>The code stays simple, but the important thing to notice is that the type of  <code>find</code>  forces us to consider the possibility of absence. This is a good thing because it means the compiler won’t let us accidentally forget about the case where a file name doesn’t have an extension. On the other hand, doing explicit case analysis like we’ve done in  <code>extension_explicit</code>  every time can get a bit tiresome.</p>

<p>In fact, the case analysis in  <code>extension_explicit</code>  follows a very common pattern:  <em>map</em>  a function on to the value inside of an  <code>Option&lt;T&gt;</code>, unless the option is  <code>None</code>, in which case, just return  <code>None</code>.</p>

<p>Rust has parametric polymorphism, so it is very easy to define a combinator that abstracts this pattern:</p>

<p>option-map</p>

<pre><code class="language-rust">fn map&lt;F, T, A&gt;(option: Option&lt;T&gt;, f: F) -&gt; Option&lt;A&gt; where F: FnOnce(T) -&gt; A {
    match option {
        None =&gt; None,
        Some(value) =&gt; Some(f(value)),
    }
}

</code></pre>

<p>Indeed,  <code>map</code>  is  <a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.map">defined as a method</a>  on  <code>Option&lt;T&gt;</code>  in the standard library.</p>

<p>Armed with our new combinator, we can rewrite our  <code>extension_explicit</code>  method to get rid of the case analysis:</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">// Returns the extension of the given file name, where the extension is defined
// as all characters succeeding the first `.`.
// If `file_name` has no `.`, then `None` is returned.
fn extension(file_name: &amp;str) -&gt; Option&lt;&amp;str&gt; {
    find(file_name, '.').map(|i| &amp;file_name[i+1..])
}

</code></pre>

<p>One other pattern that I find is very common is assigning a default value to the case when an  <code>Option</code>value is  <code>None</code>. For example, maybe your program assumes that the extension of a file is  <code>rs</code>  even if none is present. As you might imagine, the case analysis for this is not specific to file extensions—it can work with any  <code>Option&lt;T&gt;</code>:</p>

<p>option-unwrap-or</p>

<pre><code class="language-rust">fn unwrap_or&lt;T&gt;(option: Option&lt;T&gt;, default: T) -&gt; T {
    match option {
        None =&gt; default,
        Some(value) =&gt; value,
    }
}

</code></pre>

<p>The trick here is that the default value must have the same type as the value that might be inside the  <code>Option&lt;T&gt;</code>. Using it is dead simple in our case:</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">fn main() {
    assert_eq!(extension(&quot;foobar.csv&quot;).unwrap_or(&quot;rs&quot;), &quot;csv&quot;);
    assert_eq!(extension(&quot;foobar&quot;).unwrap_or(&quot;rs&quot;), &quot;rs&quot;);
}

</code></pre>

<p>(Note that  <code>unwrap_or</code>  is  <a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or">defined as a method</a>  on  <code>Option&lt;T&gt;</code>  in the standard library, so we use that here instead of the free-standing function we defined above. Don’t forget to check out the more general<a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or_else"><code>unwrap_or_else</code></a>  method.)</p>

<p>There is one more combinator that I think is worth paying special attention to:  <code>and_then</code>. It makes it easy to compose distinct computations that admit the  <em>possibility of absence</em>. For example, much of the code in this section is about finding an extension given a file name. In order to do this, you first need the file name which is typically extracted from a file  <em>path</em>. While most file paths have a file name, not  <em>all</em>  of them do. For example,  <code>.</code>,  <code>..</code>  or  <code>/</code>.</p>

<p>So, we are tasked with the challenge of finding an extension given a file  <em>path</em>. Let’s start with explicit case analysis:</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">fn file_path_ext_explicit(file_path: &amp;str) -&gt; Option&lt;&amp;str&gt; {
    match file_name(file_path) {
        None =&gt; None,
        Some(name) =&gt; match extension(name) {
            None =&gt; None,
            Some(ext) =&gt; Some(ext),
        }
    }
}

fn file_name(file_path: &amp;str) -&gt; Option&lt;&amp;str&gt; {
  // implementation elided
  unimplemented!()
}

</code></pre>

<p>You might think that we could just use the  <code>map</code>  combinator to reduce the case analysis, but its type doesn’t quite fit. Namely,  <code>map</code>  takes a function that does something only with the inner value. The result of that function is then  <em>always</em>  <a href="https://blog.burntsushi.net/rust-error-handling/#code-option-map">rewrapped with  <code>Some</code></a>. Instead, we need something like  <code>map</code>, but which allows the caller to return another  <code>Option</code>. Its generic implementation is even simpler than  <code>map</code>:</p>

<p>option-and-then</p>

<pre><code class="language-rust">fn and_then&lt;F, T, A&gt;(option: Option&lt;T&gt;, f: F) -&gt; Option&lt;A&gt;
        where F: FnOnce(T) -&gt; Option&lt;A&gt; {
    match option {
        None =&gt; None,
        Some(value) =&gt; f(value),
    }
}

</code></pre>

<p>Now we can rewrite our  <code>file_path_ext</code>  function without explicit case analysis:</p>

<p>option-ex-string-find</p>

<pre><code class="language-rust">fn file_path_ext(file_path: &amp;str) -&gt; Option&lt;&amp;str&gt; {
    file_name(file_path).and_then(extension)
}

</code></pre>

<p>The  <code>Option</code>  type has many other combinators  <a href="http://doc.rust-lang.org/std/option/enum.Option.html">defined in the standard library</a>. It is a good idea to skim this list and familiarize yourself with what’s available—they can often reduce case analysis for you. Familiarizing yourself with these combinators will pay dividends because many of them are also defined (with similar semantics) for  <code>Result</code>, which we will talk about next.</p>

<p>Combinators make using types like  <code>Option</code>  ergonomic because they reduce explicit case analysis. They are also composable because they permit the caller to handle the possibility of absence in their own way. Methods like  <code>unwrap</code>  remove choices because they will panic if  <code>Option&lt;T&gt;</code>  is  <code>None</code>.</p>

<h3 id="the-result-type">The  <code>Result</code>  type</h3>

<p>The  <code>Result</code>  type is also  <a href="http://doc.rust-lang.org/std/result/">defined in the standard library</a>:</p>

<p>result-def</p>

<pre><code class="language-rust">enum Result&lt;T, E&gt; {
    Ok(T),
    Err(E),
}

</code></pre>

<p>The  <code>Result</code>  type is a richer version of  <code>Option</code>. Instead of expressing the possibility of  <em>absence</em>  like  <code>Option</code>does,  <code>Result</code>  expresses the possibility of  <em>error</em>. Usually, the  <em>error</em>  is used to explain why the result of some computation failed. This is a strictly more general form of  <code>Option</code>. Consider the following type alias, which is semantically equivalent to the real  <code>Option&lt;T&gt;</code>  in every way:</p>

<p>option-as-result</p>

<pre><code class="language-rust">type Option&lt;T&gt; = Result&lt;T, ()&gt;;

</code></pre>

<p>This fixes the second type parameter of  <code>Result</code>  to always be  <code>()</code>  (pronounced “unit” or “empty tuple”). Exactly one value inhabits the  <code>()</code>  type:  <code>()</code>. (Yup, the type and value level terms have the same notation!)</p>

<p>The  <code>Result</code>  type is a way of representing one of two possible outcomes in a computation. By convention, one outcome is meant to be expected or “<code>Ok</code>” while the other outcome is meant to be unexpected or “<code>Err</code>”.</p>

<p>Just like  <code>Option</code>, the  <code>Result</code>  type also has an  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap"><code>unwrap</code>  method defined</a>  in the standard library. Let’s define it:</p>

<p>result-def</p>

<pre><code class="language-rust">impl&lt;T, E: ::std::fmt::Debug&gt; Result&lt;T, E&gt; {
    fn unwrap(self) -&gt; T {
        match self {
            Result::Ok(val) =&gt; val,
            Result::Err(err) =&gt;
              panic!(&quot;called `Result::unwrap()` on an `Err` value: {:?}&quot;, err),
        }
    }
}

</code></pre>

<p>This is effectively the same as our  <a href="https://blog.burntsushi.net/rust-error-handling/#code-option-def-unwrap">definition for  <code>Option::unwrap</code></a>, except it includes the error value in the  <code>panic!</code>  message. This makes debugging easier, but it also requires us to add a  <a href="http://doc.rust-lang.org/std/fmt/trait.Debug.html"><code>Debug</code></a>  constraint on the  <code>E</code>type parameter (which represents our error type). Since the vast majority of types should satisfy the  <code>Debug</code>  constraint, this tends to work out in practice. (<code>Debug</code>  on a type simply means that there’s a reasonable way to print a human readable description of values with that type.)</p>

<p>OK, let’s move on to an example.</p>

<h4 id="parsing-integers">Parsing integers</h4>

<p>The Rust standard library makes converting strings to integers dead simple. It’s so easy in fact, that it is very tempting to write something like the following:</p>

<p>result-num-unwrap</p>

<pre><code class="language-rust">fn double_number(number_str: &amp;str) -&gt; i32 {
    2 * number_str.parse::&lt;i32&gt;().unwrap()
}

fn main() {
    let n: i32 = double_number(&quot;10&quot;);
    assert_eq!(n, 20);
}

</code></pre>

<p>At this point, you should be skeptical of calling  <code>unwrap</code>. For example, if the string doesn’t parse as a number, you’ll get a panic:</p>

<pre><code class="language-text">thread '&lt;main&gt;' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', /home/rustbuild/src/rust-buildbot/slave/beta-dist-rustc-linux/build/src/libcore/result.rs:729
</code></pre>

<p>This is rather unsightly, and if this happened inside a library you’re using, you might be understandably annoyed. Instead, we should try to handle the error in our function and let the caller decide what to do. This means changing the return type of  <code>double_number</code>. But to what? Well, that requires looking at the signature of the  <a href="http://doc.rust-lang.org/std/primitive.str.html#method.parse"><code>parse</code>  method</a>  in the standard library:</p>

<pre><code class="language-rust">impl str {
    fn parse&lt;F: FromStr&gt;(&amp;self) -&gt; Result&lt;F, F::Err&gt;;
}

</code></pre>

<p>Hmm. So we at least know that we need to use a  <code>Result</code>. Certainly, it’s possible that this could have returned an  <code>Option</code>. After all, a string either parses as a number or it doesn’t, right? That’s certainly a reasonable way to go, but the implementation internally distinguishes  <em>why</em>  the string didn’t parse as an integer. (Whether it’s an empty string, an invalid digit, too big or too small.) Therefore, using a  <code>Result</code>makes sense because we want to provide more information than simply “absence.” We want to say  <em>why</em>  the parsing failed. You should try to emulate this line of reasoning when faced with a choice between  <code>Option</code>  and  <code>Result</code>. If you can provide detailed error information, then you probably should. (We’ll see more on this later.)</p>

<p>OK, but how do we write our return type? The  <code>parse</code>  method as defined above is generic over all the different number types defined in the standard library. We could (and probably should) also make our function generic, but let’s favor explicitness for the moment. We only care about  <code>i32</code>, so we need to  <a href="http://doc.rust-lang.org/std/primitive.i32.html">find its implementation of  <code>FromStr</code></a>  (do a  <code>CTRL-F</code>  in your browser for “FromStr”) and look at its  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/associated-types.html">associated type</a><code>Err</code>. We did this so we can find the concrete error type. In this case, it’s  <a href="http://doc.rust-lang.org/std/num/struct.ParseIntError.html"><code>std::num::ParseIntError</code></a>. Finally, we can rewrite our function:</p>

<p>result-num-no-unwrap</p>

<pre><code class="language-rust">use std::num::ParseIntError;

fn double_number(number_str: &amp;str) -&gt; Result&lt;i32, ParseIntError&gt; {
    match number_str.parse::&lt;i32&gt;() {
        Ok(n) =&gt; Ok(2 * n),
        Err(err) =&gt; Err(err),
    }
}

fn main() {
    match double_number(&quot;10&quot;) {
        Ok(n) =&gt; assert_eq!(n, 20),
        Err(err) =&gt; println!(&quot;Error: {:?}&quot;, err),
    }
}

</code></pre>

<p>This is a little better, but now we’ve written a lot more code! The case analysis has once again bitten us.</p>

<p>Combinators to the rescue! Just like  <code>Option</code>,  <code>Result</code>  has lots of combinators defined as methods. There is a large intersection of common combinators between  <code>Result</code>  and  <code>Option</code>. In particular,  <code>map</code>  is part of that intersection:</p>

<p>result-num-no-unwrap-map</p>

<pre><code class="language-rust">use std::num::ParseIntError;

fn double_number(number_str: &amp;str) -&gt; Result&lt;i32, ParseIntError&gt; {
    number_str.parse::&lt;i32&gt;().map(|n| 2 * n)
}

fn main() {
    match double_number(&quot;10&quot;) {
        Ok(n) =&gt; assert_eq!(n, 20),
        Err(err) =&gt; println!(&quot;Error: {:?}&quot;, err),
    }
}

</code></pre>

<p>The usual suspects are all there for  <code>Result</code>, including  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or"><code>unwrap_or</code></a>  and  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.and_then"><code>and_then</code></a>. Additionally, since  <code>Result</code>  has a second type parameter, there are combinators that affect only the error type, such as  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.map_err"><code>map_err</code></a>  (instead of  <code>map</code>) and  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.or_else"><code>or_else</code></a>  (instead of  <code>and_then</code>).</p>

<h4 id="the-result-type-alias-idiom">The  <code>Result</code>  type alias idiom</h4>

<p>In the standard library, you may frequently see types like  <code>Result&lt;i32&gt;</code>. But wait,  <a href="https://blog.burntsushi.net/rust-error-handling/#code-result-def-1">we defined  <code>Result</code></a>  to have two type parameters. How can we get away with only specifying one? The key is to define a  <code>Result</code>  type alias that  <em>fixes</em>  one of the type parameters to a particular type. Usually the fixed type is the error type. For example, our previous example parsing integers could be rewritten like this:</p>

<p>result-num-no-unwrap-map-alias</p>

<pre><code class="language-rust">use std::num::ParseIntError;
use std::result;

type Result&lt;T&gt; = result::Result&lt;T, ParseIntError&gt;;

fn double_number(number_str: &amp;str) -&gt; Result&lt;i32&gt; {
    unimplemented!();
}

</code></pre>

<p>Why would we do this? Well, if we have a lot of functions that could return  <code>ParseIntError</code>, then it’s much more convenient to define an alias that always uses  <code>ParseIntError</code>  so that we don’t have to write it out all the time.</p>

<p>The most prominent place this idiom is used in the standard library is with  <a href="http://doc.rust-lang.org/std/io/type.Result.html"><code>io::Result</code></a>. Typically, one writes  <code>io::Result&lt;T&gt;</code>, which makes it clear that you’re using the  <code>io</code>  module’s type alias instead of the plain definition from  <code>std::result</code>. (This idiom is also used for  <a href="http://doc.rust-lang.org/std/fmt/type.Result.html"><code>fmt::Result</code></a>.)</p>

<h3 id="a-brief-interlude-unwrapping-isn-t-evil">A brief interlude: unwrapping isn’t evil</h3>

<p>If you’ve been following along, you might have noticed that I’ve taken a pretty hard line against calling methods like  <code>unwrap</code>  that could  <code>panic</code>  and abort your program.  <em>Generally speaking</em>, this is good advice.</p>

<p>However,  <code>unwrap</code>  can still be used judiciously. What exactly justifies use of  <code>unwrap</code>  is somewhat of a grey area and reasonable people can disagree. I’ll summarize some of my  <em>opinions</em>  on the matter.</p>

<ul>
<li><strong>In examples and quick ‘n’ dirty code.</strong>  Sometimes you’re writing examples or a quick program, and error handling simply isn’t important. Beating the convenience of  <code>unwrap</code>  can be hard in such scenarios, so it is very appealing.</li>
<li><strong>When panicking indicates a bug in the program.</strong>  When the invariants of your code should prevent a certain case from happening (like, say, popping from an empty stack), then panicking can be permissible. This is because it exposes a bug in your program. This can be explicit, like from an  <code>assert!</code>  failing, or it could be because your index into an array was out of bounds.</li>
</ul>

<p>This is probably not an exhaustive list. Moreover, when using an  <code>Option</code>, it is often better to use its<a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.expect"><code>expect</code></a>  method.  <code>expect</code>  does exactly the same thing as  <code>unwrap</code>, except it prints a message you give to  <code>expect</code>. This makes the resulting panic a bit nicer to deal with, since it will show your message instead of “called unwrap on a  <code>None</code>  value.”</p>

<p>My advice boils down to this: use good judgment. There’s a reason why the words “never do X” or “Y is considered harmful” don’t appear in my writing. There are trade offs to all things, and it is up to you as the programmer to determine what is acceptable for your use cases. My goal is only to help you evaluate trade offs as accurately as possible.</p>

<p>Now that we’ve covered the basics of error handling in Rust, and I’ve said my piece about unwrapping, let’s start exploring more of the standard library.</p>

<h2 id="working-with-multiple-error-types">Working with multiple error types</h2>

<p>Thus far, we’ve looked at error handling where everything was either an  <code>Option&lt;T&gt;</code>  or a  <code>Result&lt;T, SomeError&gt;</code>. But what happens when you have both an  <code>Option</code>  and a  <code>Result</code>? Or what if you have a  <code>Result&lt;T, Error1&gt;</code>  and a  <code>Result&lt;T, Error2&gt;</code>? Handling  <em>composition of distinct error types</em>  is the next challenge in front of us, and it will be the major theme throughout the rest of this article.</p>

<h3 id="composing-option-and-result">Composing  <code>Option</code>  and  <code>Result</code></h3>

<p>So far, I’ve talked about combinators defined for  <code>Option</code>  and combinators defined for  <code>Result</code>. We can use these combinators to compose results of different computations without doing explicit case analysis.</p>

<p>Of course, in real code, things aren’t always as clean. Sometimes you have a mix of  <code>Option</code>  and  <code>Result</code>types. Must we resort to explicit case analysis, or can we continue using combinators?</p>

<p>For now, let’s revisit one of the first examples in this article:</p>

<pre><code class="language-rust">use std::env;

fn main() {
    let mut argv = env::args();
    let arg: String = argv.nth(1).unwrap(); // error 1
    let n: i32 = arg.parse().unwrap(); // error 2
    println!(&quot;{}&quot;, 2 * n);
}

// $ cargo run --bin unwrap-double 5
// 10

</code></pre>

<p>Given our new found knowledge of  <code>Option</code>,  <code>Result</code>  and their various combinators, we should try to rewrite this so that errors are handled properly and the program doesn’t panic if there’s an error.</p>

<p>The tricky aspect here is that  <code>argv.nth(1)</code>  produces an  <code>Option</code>  while  <code>arg.parse()</code>  produces a  <code>Result</code>. These aren’t directly composable. When faced with both an  <code>Option</code>  and a  <code>Result</code>, the solution is  <em>usually</em>  to convert the  <code>Option</code>  to a  <code>Result</code>. In our case, the absence of a command line parameter (from  <code>env::args()</code>) means the user didn’t invoke the program correctly. We could just use a  <code>String</code>  to describe the error. Let’s try:</p>

<p>error-double-string</p>

<pre><code class="language-rust">use std::env;

fn double_arg(mut argv: env::Args) -&gt; Result&lt;i32, String&gt; {
    argv.nth(1)
        .ok_or(&quot;Please give at least one argument&quot;.to_owned())
        .and_then(|arg| arg.parse::&lt;i32&gt;().map_err(|err| err.to_string()))
}

fn main() {
    match double_arg(env::args()) {
        Ok(n) =&gt; println!(&quot;{}&quot;, n),
        Err(err) =&gt; println!(&quot;Error: {}&quot;, err),
    }
}

</code></pre>

<p>There are a couple new things in this example. The first is the use of the  <a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or"><code>Option::ok_or</code></a>  combinator. This is one way to convert an  <code>Option</code>  into a  <code>Result</code>. The conversion requires you to specify what error to use if  <code>Option</code>  is  <code>None</code>. Like the other combinators we’ve seen, its definition is very simple:</p>

<p>option-ok-or-def</p>

<pre><code class="language-rust">fn ok_or&lt;T, E&gt;(option: Option&lt;T&gt;, err: E) -&gt; Result&lt;T, E&gt; {
    match option {
        Some(val) =&gt; Ok(val),
        None =&gt; Err(err),
    }
}

</code></pre>

<p>The other new combinator used here is  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.map_err"><code>Result::map_err</code></a>. This is just like  <code>Result::map</code>, except it maps a function on to the  <em>error</em>  portion of a  <code>Result</code>  value. If the  <code>Result</code>  is an  <code>Ok(...)</code>  value, then it is returned unmodified.</p>

<p>We use  <code>map_err</code>  here because it is necessary for the error types to remain the same (because of our use of  <code>and_then</code>). Since we chose to convert the  <code>Option&lt;String&gt;</code>  (from  <code>argv.nth(1)</code>) to a  <code>Result&lt;String, String&gt;</code>, we must also convert the  <code>ParseIntError</code>  from  <code>arg.parse()</code>  to a  <code>String</code>.</p>

<h3 id="the-limits-of-combinators">The limits of combinators</h3>

<p>Doing IO and parsing input is a very common task, and it’s one that I personally have done a lot of in Rust. Therefore, we will use (and continue to use) IO and various parsing routines to exemplify error handling.</p>

<p>Let’s start simple. We are tasked with opening a file, reading all of its contents and converting its contents to a number. Then we multiply it by  <code>2</code>  and print the output.</p>

<p>Although I’ve tried to convince you not to use  <code>unwrap</code>, it can be useful to first write your code using  <code>unwrap</code>. It allows you to focus on your problem instead of the error handling, and it exposes the points where proper error handling need to occur. Let’s start there so we can get a handle on the code, and then refactor it to use better error handling.</p>

<p>io-basic-unwrap</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; i32 {
    let mut file = File::open(file_path).unwrap(); // error 1
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents).unwrap(); // error 2
    let n: i32 = contents.trim().parse().unwrap(); // error 3
    2 * n
}

fn main() {
    let doubled = file_double(&quot;foobar&quot;);
    println!(&quot;{}&quot;, doubled);
}

</code></pre>

<p>(N.B. The  <code>AsRef&lt;Path&gt;</code>  is used because those are the  <a href="http://doc.rust-lang.org/std/fs/struct.File.html#method.open">same bounds used on  <code>std::fs::File::open</code></a>. This makes it ergnomic to use any kind of string as a file path.)</p>

<p>There are three different errors that can occur here:</p>

<ol>
<li>A problem opening the file.</li>
<li>A problem reading data from the file.</li>
<li>A problem parsing the data as a number.</li>
</ol>

<p>The first two problems are described via the  <a href="http://doc.rust-lang.org/std/io/struct.Error.html"><code>std::io::Error</code></a>  type. We know this because of the return types of  <a href="http://doc.rust-lang.org/std/fs/struct.File.html#method.open"><code>std::fs::File::open</code></a>  and  <a href="http://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_string"><code>std::io::Read::read_to_string</code></a>. (Note that they both use the  <a href="https://blog.burntsushi.net/rust-error-handling/#the-result-type-alias-idiom"><code>Result</code>  type alias idiom</a>  described previously. If you click on the  <code>Result</code>  type, you’ll  <a href="http://doc.rust-lang.org/std/io/type.Result.html">see the type alias</a>, and consequently, the underlying  <code>io::Error</code>  type.) The third problem is described by the<a href="http://doc.rust-lang.org/std/num/struct.ParseIntError.html"><code>std::num::ParseIntError</code></a>  type. The  <code>io::Error</code>  type in particular is  <em>pervasive</em>  throughout the standard library. You will see it again and again.</p>

<p>Let’s start the process of refactoring the  <code>file_double</code>  function. To make this function composable with other components of the program, it should  <em>not</em>  panic if any of the above error conditions are met. Effectively, this means that the function should  <em>return an error</em>  if any of its operations fail. Our problem is that the return type of  <code>file_double</code>  is  <code>i32</code>, which does not give us any useful way of reporting an error. Thus, we must start by changing the return type from  <code>i32</code>  to something else.</p>

<p>The first thing we need to decide: should we use  <code>Option</code>  or  <code>Result</code>? We certainly could use  <code>Option</code>  very easily. If any of the three errors occur, we could simply return  <code>None</code>. This will work  <em>and it is better than panicking</em>, but we can do a lot better. Instead, we should pass some detail about the error that occurred. Since we want to express the  <em>possibility of error</em>, we should use  <code>Result&lt;i32, E&gt;</code>. But what should  <code>E</code>  be? Since two  <em>different</em>  types of errors can occur, we need to convert them to a common type. One such type is  <code>String</code>. Let’s see how that impacts our code:</p>

<p>io-basic-error-string</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, String&gt; {
    File::open(file_path)
         .map_err(|err| err.to_string())
         .and_then(|mut file| {
              let mut contents = String::new();
              file.read_to_string(&amp;mut contents)
                  .map_err(|err| err.to_string())
                  .map(|_| contents)
         })
         .and_then(|contents| {
              contents.trim().parse::&lt;i32&gt;()
                      .map_err(|err| err.to_string())
         })
         .map(|n| 2 * n)
}

fn main() {
    match file_double(&quot;foobar&quot;) {
        Ok(n) =&gt; println!(&quot;{}&quot;, n),
        Err(err) =&gt; println!(&quot;Error: {}&quot;, err),
    }
}

</code></pre>

<p>This code looks a bit hairy. It can take quite a bit of practice before code like this becomes easy to write. The way I write it is by  <em>following the types</em>. As soon as I changed the return type of  <code>file_double</code>  to<code>Result&lt;i32, String&gt;</code>, I had to start looking for the right combinators. In this case, we only used three different combinators:  <code>and_then</code>,  <code>map</code>  and  <code>map_err</code>.</p>

<p><code>and_then</code>  is used to chain multiple computations where each computation could return an error. After opening the file, there are two more computations that could fail: reading from the file and parsing the contents as a number. Correspondingly, there are two calls to  <code>and_then</code>.</p>

<p><code>map</code>  is used to apply a function to the  <code>Ok(...)</code>  value of a  <code>Result</code>. For example, the very last call to  <code>map</code>multiplies the  <code>Ok(...)</code>  value (which is an  <code>i32</code>) by  <code>2</code>. If an error had occurred before that point, this operation would have been skipped because of how  <code>map</code>  is defined.</p>

<p><code>map_err</code>  is the trick the makes all of this work.  <code>map_err</code>  is just like  <code>map</code>, except it applies a function to the  <code>Err(...)</code>  value of a  <code>Result</code>. In this case, we want to convert all of our errors to one type:  <code>String</code>. Since both  <code>io::Error</code>  and  <code>num::ParseIntError</code>  implement  <code>ToString</code>, we can call the  <code>to_string()</code>  method to convert them.</p>

<p>With all of that said, the code is still hairy. Mastering use of combinators is important, but they have their limits. Let’s try a different approach: early returns.</p>

<h3 id="early-returns">Early returns</h3>

<p>I’d like to take the code from the previous section and rewrite it using  <em>early returns</em>. Early returns let you exit the function early. We can’t return early in  <code>file_double</code>  from inside another closure, so we’ll need to revert back to explicit case analysis.</p>

<p>io-basic-error-string-early-return</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, String&gt; {
    let mut file = match File::open(file_path) {
        Ok(file) =&gt; file,
        Err(err) =&gt; return Err(err.to_string()),
    };
    let mut contents = String::new();
    if let Err(err) = file.read_to_string(&amp;mut contents) {
        return Err(err.to_string());
    }
    let n: i32 = match contents.trim().parse() {
        Ok(n) =&gt; n,
        Err(err) =&gt; return Err(err.to_string()),
    };
    Ok(2 * n)
}

fn main() {
    match file_double(&quot;foobar&quot;) {
        Ok(n) =&gt; println!(&quot;{}&quot;, n),
        Err(err) =&gt; println!(&quot;Error: {}&quot;, err),
    }
}

</code></pre>

<p>Reasonable people can disagree over whether this code is better that the code that uses combinators, but if you aren’t familiar with the combinator approach, this code looks simpler to read to me. It uses explicit case analysis with  <code>match</code>  and  <code>if let</code>. If an error occurs, it simply stops executing the function and returns the error (by converting it to a string).</p>

<p>Isn’t this a step backwards though? Previously, I said that the key to ergonomic error handling is reducing explicit case analysis, yet we’ve reverted back to explicit case analysis here. It turns out, there are  <em>multiple</em>  ways to reduce explicit case analysis. Combinators aren’t the only way.</p>

<h3 id="the-try-macro-operator">The  <code>try!</code>  macro/<code>?</code>  operator</h3>

<p>In older versions of Rust (Rust 1.12 or older), a cornerstone of error handling in Rust is the  <code>try!</code>  macro. The  <code>try!</code>  macro abstracts case analysis just like combinators, but unlike combinators, it also abstracts  <em>control flow</em>. Namely, it can abstract the  <em>early return</em>  pattern seen above.</p>

<p>Here is a simplified definition of a  <code>try!</code>  macro:</p>

<p>try-def-simple</p>

<pre><code class="language-rust">macro_rules! try {
    ($e:expr) =&gt; (match $e {
        Ok(val) =&gt; val,
        Err(err) =&gt; return Err(err),
    });
}

</code></pre>

<p>(The  <a href="http://doc.rust-lang.org/std/macro.try!.html">real definition</a>  is a bit more sophisticated. We will address that later.)</p>

<p>Using the  <code>try!</code>  macro makes it very easy to simplify our last example. Since it does the case analysis and the early return for us, we get tighter code that is easier to read:</p>

<p>io-basic-error-try</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, String&gt; {
    let mut file = try!(File::open(file_path).map_err(|e| e.to_string()));
    let mut contents = String::new();
    try!(file.read_to_string(&amp;mut contents).map_err(|e| e.to_string()));
    let n = try!(contents.trim().parse::&lt;i32&gt;().map_err(|e| e.to_string()));
    Ok(2 * n)
}

fn main() {
    match file_double(&quot;foobar&quot;) {
        Ok(n) =&gt; println!(&quot;{}&quot;, n),
        Err(err) =&gt; println!(&quot;Error: {}&quot;, err),
    }
}

</code></pre>

<p>The  <code>map_err</code>  calls are still necessary given  <a href="https://blog.burntsushi.net/rust-error-handling/#code-try-def-simple">our definition of  <code>try!</code></a>. This is because the error types still need to be converted to  <code>String</code>. The good news is that we will soon learn how to remove those  <code>map_err</code>calls! The bad news is that we will need to learn a bit more about a couple important traits in the standard library before we can remove the  <code>map_err</code>  calls.</p>

<p>In newer versions of Rust (Rust 1.13 or newer), the  <code>try!</code>  macro was replaced with the  <code>?</code>  operator. While it is intended to grow new powers that we won’t cover here, using  <code>?</code>  instead of  <code>try!</code>  is simple:</p>

<p>io-basic-error-question</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, String&gt; {
    let mut file = File::open(file_path).map_err(|e| e.to_string())?;
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents).map_err(|e| e.to_string())?;
    let n = contents.trim().parse::&lt;i32&gt;().map_err(|e| e.to_string())?;
    Ok(2 * n)
}

fn main() {
    match file_double(&quot;foobar&quot;) {
        Ok(n) =&gt; println!(&quot;{}&quot;, n),
        Err(err) =&gt; println!(&quot;Error: {}&quot;, err),
    }
}

</code></pre>

<h3 id="defining-your-own-error-type">Defining your own error type</h3>

<p>Before we dive into some of the standard library error traits, I’d like to wrap up this section by removing the use of  <code>String</code>  as our error type in the previous examples.</p>

<p>Using  <code>String</code>  as we did in our previous examples is convenient because it’s easy to convert errors to strings, or even make up your own errors as strings on the spot. However, using  <code>String</code>  for your errors has some downsides.</p>

<p>The first downside is that the error messages tend to clutter your code. It’s possible to define the error messages elsewhere, but unless you’re unusually disciplined, it is very tempting to embed the error message into your code. Indeed, we did exactly this in a  <a href="https://blog.burntsushi.net/rust-error-handling/#code-error-double-string">previous example</a>.</p>

<p>The second and more important downside is that  <code>String</code>s are  <em>lossy</em>. That is, if all errors are converted to strings, then the errors we pass to the caller become completely opaque. The only reasonable thing the caller can do with a  <code>String</code>  error is show it to the user. Certainly, inspecting the string to determine the type of error is not robust. (Admittedly, this downside is far more important inside of a library as opposed to, say, an application.)</p>

<p>For example, the  <code>io::Error</code>  type embeds an  <a href="http://doc.rust-lang.org/std/io/enum.ErrorKind.html"><code>io::ErrorKind</code></a>, which is  <em>structured data</em>  that represents what went wrong during an IO operation. This is important because you might want to react differently depending on the error. (e.g., A  <code>BrokenPipe</code>  error might mean quitting your program gracefully while a  <code>NotFound</code>  error might mean exiting with an error code and showing an error to the user.) With  <code>io::ErrorKind</code>, the caller can examine the type of an error with case analysis, which is strictly superior to trying to tease out the details of an error inside of a  <code>String</code>.</p>

<p>Instead of using a  <code>String</code>  as an error type in our previous example of reading an integer from a file, we can define our own error type that represents errors with  <em>structured data</em>. We endeavor to not drop information from underlying errors in case the caller wants to inspect the details.</p>

<p>The ideal way to represent  <em>one of many possibilities</em>  is to define our own sum type using  <code>enum</code>. In our case, an error is either an  <code>io::Error</code>  or a  <code>num::ParseIntError</code>, so a natural definition arises:</p>

<p>io-basic-error-custom</p>

<pre><code class="language-rust">use std::io;
use std::num;

// We derive `Debug` because all types should probably derive `Debug`.
// This gives us a reasonable human readable description of `CliError` values.
#[derive(Debug)]
enum CliError {
    Io(io::Error),
    Parse(num::ParseIntError),
}

</code></pre>

<p>Tweaking our code is very easy. Instead of converting errors to strings, we simply convert them to our  <code>CliError</code>  type using the corresponding value constructor:</p>

<p>io-basic-error-custom</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, CliError&gt; {
    let mut file = File::open(file_path).map_err(CliError::Io)?;
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents).map_err(CliError::Io)?;
    let n: i32 = contents.trim().parse().map_err(CliError::Parse)?;
    Ok(2 * n)
}

fn main() {
    match file_double(&quot;foobar&quot;) {
        Ok(n) =&gt; println!(&quot;{}&quot;, n),
        Err(err) =&gt; println!(&quot;Error: {:?}&quot;, err),
    }
}

</code></pre>

<p>The only change here is switching  <code>map_err(|e| e.to_string())</code>  (which converts errors to strings) to  <code>map_err(CliError::Io)</code>  or  <code>map_err(CliError::Parse)</code>. The  <em>caller</em>  gets to decide the level of detail to report to the user. In effect, using a  <code>String</code>  as an error type removes choices from the caller while using a custom  <code>enum</code>  error type like  <code>CliError</code>  gives the caller all of the conveniences as before in addition to  <em>structured data</em>  describing the error.</p>

<p>A rule of thumb is to define your own error type, but a  <code>String</code>  error type will do in a pinch, particularly if you’re writing an application. If you’re writing a library, defining your own error type should be strongly preferred so that you don’t remove choices from the caller unnecessarily.</p>

<h2 id="standard-library-traits-used-for-error-handling">Standard library traits used for error handling</h2>

<p>The standard library defines two integral traits for error handling:  <a href="http://doc.rust-lang.org/std/error/trait.Error.html"><code>std::error::Error</code></a>  and<a href="http://doc.rust-lang.org/std/convert/trait.From.html"><code>std::convert::From</code></a>. While  <code>Error</code>  is designed specifically for generically describing errors, the  <code>From</code>  trait serves a more general role for converting values between two distinct types.</p>

<h3 id="the-error-trait">The  <code>Error</code>  trait</h3>

<p>The  <code>Error</code>  trait is  <a href="http://doc.rust-lang.org/std/error/trait.Error.html">defined in the standard library</a>:</p>

<p>error-def</p>

<pre><code class="language-rust">use std::fmt::{Debug, Display};

trait Error: Debug + Display {
  /// A short description of the error.
  fn description(&amp;self) -&gt; &amp;str;

  /// The lower level cause of this error, if any.
  fn cause(&amp;self) -&gt; Option&lt;&amp;Error&gt; { None }
}

</code></pre>

<p>This trait is super generic because it is meant to be implemented for  <em>all</em>  types that represent errors. This will prove useful for writing composable code as we’ll see later. Otherwise, the trait allows you to do at least the following things:</p>

<ul>
<li>Obtain a  <code>Debug</code>  representation of the error.</li>
<li>Obtain a user-facing  <code>Display</code>  representation of the error.</li>
<li>Obtain a short description of the error (via the  <code>description</code>  method).</li>
<li>Inspect the causal chain of an error, if one exists (via the  <code>cause</code>  method).</li>
</ul>

<p>The first two are a result of  <code>Error</code>  requiring impls for both  <code>Debug</code>  and  <code>Display</code>. The latter two are from the two methods defined on  <code>Error</code>. The power of  <code>Error</code>  comes from the fact that all error types impl  <code>Error</code>, which means errors can be existentially quantified as a  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/trait-objects.html">trait object</a>. This manifests as either  <code>Box&lt;Error&gt;</code>or  <code>&amp;Error</code>. Indeed, the  <code>cause</code>  method returns an  <code>&amp;Error</code>, which is itself a trait object. We’ll revisit the  <code>Error</code>trait’s utility as a trait object later.</p>

<p>For now, it suffices to show an example implementing the  <code>Error</code>  trait. Let’s use the error type we defined in the  <a href="https://blog.burntsushi.net/rust-error-handling/#defining-your-own-error-type">previous section</a>:</p>

<p>error-impl</p>

<pre><code class="language-rust">use std::io;
use std::num;

// We derive `Debug` because all types should probably derive `Debug`.
// This gives us a reasonable human readable description of `CliError` values.
#[derive(Debug)]
enum CliError {
    Io(io::Error),
    Parse(num::ParseIntError),
}

</code></pre>

<p>This particular error type represents the possibility of two types of errors occurring: an error dealing with I/O or an error converting a string to a number. The error could represent as many error types as you want by adding new variants to the  <code>enum</code>  definition.</p>

<p>Implementing  <code>Error</code>  is pretty straight-forward. It’s mostly going to be a lot explicit case analysis.</p>

<p>error-impl</p>

<pre><code class="language-rust">use std::error;
use std::fmt;

impl fmt::Display for CliError {
    fn fmt(&amp;self, f: &amp;mut fmt::Formatter) -&gt; fmt::Result {
        match *self {
            // Both underlying errors already impl `Display`, so we defer to
            // their implementations.
            CliError::Io(ref err) =&gt; write!(f, &quot;IO error: {}&quot;, err),
            CliError::Parse(ref err) =&gt; write!(f, &quot;Parse error: {}&quot;, err),
        }
    }
}

impl error::Error for CliError {
    fn description(&amp;self) -&gt; &amp;str {
        // Both underlying errors already impl `Error`, so we defer to their
        // implementations.
        match *self {
            CliError::Io(ref err) =&gt; err.description(),
            // Normally we can just write `err.description()`, but the error
            // type has a concrete method called `description`, which conflicts
            // with the trait method. For now, we must explicitly call
            // `description` through the `Error` trait.
            CliError::Parse(ref err) =&gt; error::Error::description(err),
        }
    }

    fn cause(&amp;self) -&gt; Option&lt;&amp;error::Error&gt; {
        match *self {
            // N.B. Both of these implicitly cast `err` from their concrete
            // types (either `&amp;io::Error` or `&amp;num::ParseIntError`)
            // to a trait object `&amp;Error`. This works because both error types
            // implement `Error`.
            CliError::Io(ref err) =&gt; Some(err),
            CliError::Parse(ref err) =&gt; Some(err),
        }
    }
}

</code></pre>

<p>I note that this is a very typical implementation of  <code>Error</code>: match on your different error types and satisfy the contracts defined for  <code>description</code>  and  <code>cause</code>.</p>

<h3 id="the-from-trait">The  <code>From</code>  trait</h3>

<p>The  <code>std::convert::From</code>  trait is  <a href="http://doc.rust-lang.org/std/convert/trait.From.html">defined in the standard library</a>:</p>

<p>from-def</p>

<pre><code class="language-rust">trait From&lt;T&gt; {
    fn from(T) -&gt; Self;
}

</code></pre>

<p>Deliciously simple, yes?  <code>From</code>  is very useful because it gives us a generic way to talk about conversion  <em>from</em>  a particular type  <code>T</code>  to some other type (in this case, “some other type” is the subject of the impl, or  <code>Self</code>). The crux of  <code>From</code>  is the  <a href="http://doc.rust-lang.org/std/convert/trait.From.html">set of implementations provided by the standard library</a>.</p>

<p>Here are a few simple examples demonstrating how  <code>From</code>  works:</p>

<p>from-examples</p>

<pre><code class="language-rust">let string: String = From::from(&quot;foo&quot;);
let bytes: Vec&lt;u8&gt; = From::from(&quot;foo&quot;);
let cow: ::std::borrow::Cow&lt;str&gt; = From::from(&quot;foo&quot;);

</code></pre>

<p>OK, so  <code>From</code>  is useful for converting between strings. But what about errors? It turns out, there is one critical impl:</p>

<pre><code class="language-rust">impl&lt;'a, E: Error + 'a&gt; From&lt;E&gt; for Box&lt;Error + 'a&gt;

</code></pre>

<p>This impl says that for  <em>any</em>  type that impls  <code>Error</code>, we can convert it to a trait object  <code>Box&lt;Error&gt;</code>. This may not seem terribly surprising, but it is useful in a generic context.</p>

<p>Remember the two errors we were dealing with previously? Specifically,  <code>io::Error</code>  and  <code>num::ParseIntError</code>. Since both impl  <code>Error</code>, they work with  <code>From</code>:</p>

<p>from-examples-errors</p>

<pre><code class="language-rust">use std::error::Error;
use std::fs;
use std::io;
use std::num;

// We have to jump through some hoops to actually get error values.
let io_err: io::Error = io::Error::last_os_error();
let parse_err: num::ParseIntError = &quot;not a number&quot;.parse::&lt;i32&gt;().unwrap_err();

// OK, here are the conversions.
let err1: Box&lt;Error&gt; = From::from(io_err);
let err2: Box&lt;Error&gt; = From::from(parse_err);

</code></pre>

<p>There is a really important pattern to recognize here. Both  <code>err1</code>  and  <code>err2</code>  have the  <em>same type</em>. This is because they are existentially quantified types, or trait objects. In particularly, their underlying type is  <em>erased</em>  from the compiler’s knowledge, so it truly sees  <code>err1</code>  and  <code>err2</code>  as exactly the same. Additionally, we constructed  <code>err1</code>  and  <code>err2</code>  using precisely the same function call:  <code>From::from</code>. This is because  <code>From::from</code>  is overloaded on both its argument and its return type.</p>

<p>This pattern is important because it solves a problem we had earlier: it gives us a way to reliably convert errors to the same type using the same function.</p>

<p>Time to revisit an old friend; the  <code>try!</code>  macro/<code>?</code>  operator.</p>

<h3 id="the-real-try-macro-operator">The real  <code>try!</code>  macro/<code>?</code>  operator</h3>

<p>Previously, I presented this definition of  <code>try!</code>:</p>

<pre><code class="language-rust">macro_rules! try {
    ($e:expr) =&gt; (match $e {
        Ok(val) =&gt; val,
        Err(err) =&gt; return Err(err),
    });
}

</code></pre>

<p>This is not it’s real definition. It’s real definition is  <a href="http://doc.rust-lang.org/std/macro.try!.html">in the standard library</a>:</p>

<p>try-def</p>

<pre><code class="language-rust">macro_rules! try {
    ($e:expr) =&gt; (match $e {
        Ok(val) =&gt; val,
        Err(err) =&gt; return Err(::std::convert::From::from(err)),
    });
}

</code></pre>

<p>There’s one tiny but powerful change: the error value is passed through  <code>From::from</code>. This makes the  <code>try!</code>macro a lot more powerful because it gives you automatic type conversion for free. This is also very similar to how the  <code>?</code>  operator works, which is defined slightly differently. Namely,  <code>x?</code>  desugars to something like the following:</p>

<p>questionmark-def</p>

<pre><code class="language-rust">match ::std::ops::Try::into_result(x) {
    Ok(v) =&gt; v,
    Err(e) =&gt; return ::std::ops::Try::from_error(From::from(e)),
}

</code></pre>

<p>The  <a href="https://doc.rust-lang.org/std/ops/trait.Try.html"><code>Try</code>  trait</a>  is still unstable and beyond the scope of this article, but the essence of it is that it provides a way to abstract over many different types of success/failure scenarios, without being tightly coupled to  <code>Result&lt;T, E&gt;</code>. As you can see though, the  <code>x?</code>  syntax still calls  <code>From::from</code>, which is how we achieve automatic error conversion.</p>

<p>Since most code written today uses  <code>?</code>  instead of  <code>try!</code>, we will use  <code>?</code>  for the remainder of this post.</p>

<p>Let’s take a look at code we wrote previously to read a file and convert its contents to an integer:</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, String&gt; {
    let mut file = File::open(file_path).map_err(|e| e.to_string())?;
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents).map_err(|e| e.to_string())?;
    let n = contents.trim().parse::&lt;i32&gt;().map_err(|e| e.to_string())?;
    Ok(2 * n)
}

</code></pre>

<p>Earlier, I promised that we could get rid of the  <code>map_err</code>  calls. Indeed, all we have to do is pick a type that  <code>From</code>  works with. As we saw in the previous section,  <code>From</code>  has an impl that let’s it convert any error type into a  <code>Box&lt;Error&gt;</code>:</p>

<p>io-basic-error-try-from</p>

<pre><code class="language-rust">use std::error::Error;
use std::fs::File;
use std::io::Read;
use std::path::Path;

fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, Box&lt;Error&gt;&gt; {
    let mut file = File::open(file_path)?;
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents)?;
    let n = contents.trim().parse::&lt;i32&gt;()?;
    Ok(2 * n)
}

</code></pre>

<p>We are getting very close to ideal error handling. Our code has very little overhead as a result from error handling because the  <code>?</code>  operator encapsulates three things simultaneously:</p>

<ol>
<li>Case analysis.</li>
<li>Control flow.</li>
<li>Error type conversion.</li>
</ol>

<p>When all three things are combined, we get code that is unencumbered by combinators, calls to  <code>unwrap</code>or case analysis.</p>

<p>There’s one little nit left: the  <code>Box&lt;Error&gt;</code>  type is  <em>opaque</em>. If we return a  <code>Box&lt;Error&gt;</code>  to the caller, the caller can’t (easily) inspect underlying error type. The situation is certainly better than  <code>String</code>  because the caller can call methods like  <a href="http://doc.rust-lang.org/std/error/trait.Error.html#tymethod.description"><code>description</code></a>  and  <a href="http://doc.rust-lang.org/std/error/trait.Error.html#method.cause"><code>cause</code></a>, but the limitation remains:  <code>Box&lt;Error&gt;</code>  is opaque. (N.B. This isn’t entirely true because Rust does have runtime reflection, which is useful in some scenarios that are  <a href="https://crates.io/crates/error">beyond the scope of this article</a>.)</p>

<p>It’s time to revisit our custom  <code>CliError</code>  type and tie everything together.</p>

<h3 id="composing-custom-error-types">Composing custom error types</h3>

<p>In the last section, we looked at the real  <code>?</code>  operator and how it does automatic type conversion for us by calling  <code>From::from</code>  on the error value. In particular, we converted errors to  <code>Box&lt;Error&gt;</code>, which works, but the type is opaque to callers.</p>

<p>To fix this, we use the same remedy that we’re already familiar with: a custom error type. Once again, here is the code that reads the contents of a file and converts it to an integer:</p>

<p>io-basic-error-custom-from</p>

<pre><code class="language-rust">use std::fs::File;
use std::io::{self, Read};
use std::num;
use std::path::Path;

// We derive `Debug` because all types should probably derive `Debug`.
// This gives us a reasonable human readable description of `CliError` values.
#[derive(Debug)]
enum CliError {
    Io(io::Error),
    Parse(num::ParseIntError),
}

fn file_double_verbose&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, CliError&gt; {
    let mut file = File::open(file_path).map_err(CliError::Io)?;
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents).map_err(CliError::Io)?;
    let n: i32 = contents.trim().parse().map_err(CliError::Parse)?;
    Ok(2 * n)
}

</code></pre>

<p>Notice that we still have the calls to  <code>map_err</code>. Why? Well, recall the definitions of the  <a href="https://blog.burntsushi.net/rust-error-handling/#code-questionmark-def"><code>?</code>  operator</a>  and  <a href="https://blog.burntsushi.net/rust-error-handling/#code-from-def"><code>From</code></a>. The problem is that there is no  <code>From</code>  impl that allows us to convert from error types like  <code>io::Error</code>  and  <code>num::ParseIntError</code>  to our own custom  <code>CliError</code>. Of course, it is easy to fix this! Since we defined  <code>CliError</code>, we can impl  <code>From</code>  with it:</p>

<p>io-basic-error-custom-from</p>

<pre><code class="language-rust">impl From&lt;io::Error&gt; for CliError {
    fn from(err: io::Error) -&gt; CliError {
        CliError::Io(err)
    }
}

impl From&lt;num::ParseIntError&gt; for CliError {
    fn from(err: num::ParseIntError) -&gt; CliError {
        CliError::Parse(err)
    }
}

</code></pre>

<p>All these impls are doing is teaching  <code>From</code>  how to create a  <code>CliError</code>  from other error types. In our case, construction is as simple as invoking the corresponding value constructor. Indeed, it is  <em>typically</em>  this easy.</p>

<p>We can finally rewrite  <code>file_double</code>:</p>

<p>io-basic-error-custom-from</p>

<pre><code class="language-rust">fn file_double&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P) -&gt; Result&lt;i32, CliError&gt; {
    let mut file = File::open(file_path)?;
    let mut contents = String::new();
    file.read_to_string(&amp;mut contents)?;
    let n: i32 = contents.trim().parse()?;
    Ok(2 * n)
}

</code></pre>

<p>The only thing we did here was remove the calls to  <code>map_err</code>. They are no longer needed because the  <code>?</code>operator invokes  <code>From::from</code>  on the error value. This works because we’ve provided  <code>From</code>  impls for all the error types that could appear.</p>

<p>If we modified our  <code>file_double</code>  function to perform some other operation, say, convert a string to a float, then we’d need to add a new variant to our error type:</p>

<pre><code class="language-rust">enum CliError {
    Io(io::Error),
    ParseInt(num::ParseIntError),
    ParseFloat(num::ParseFloatError),
}

</code></pre>

<p>And add a new  <code>From</code>  impl:</p>

<pre><code class="language-rust">impl From&lt;num::ParseFloatError&gt; for CliError {
    fn from(err: num::ParseFloatError) -&gt; CliError {
        CliError::Parse(err)
    }
}

</code></pre>

<p>And that’s it!</p>

<h3 id="advice-for-library-writers">Advice for library writers</h3>

<p>Idioms for Rust libraries are still forming, but if your library needs to report custom errors, then you should probably define your own error type. It’s up to you whether or not to expose its representation (like  <a href="http://doc.rust-lang.org/std/io/enum.ErrorKind.html"><code>ErrorKind</code></a>) or keep it hidden (like  <a href="http://doc.rust-lang.org/std/num/struct.ParseIntError.html"><code>ParseIntError</code></a>). Regardless of how you do it, it’s usually good practice to at least provide some information about the error beyond just its  <code>String</code>  representation. But certainly, this will vary depending on use cases.</p>

<p>At a minimum, you should probably implement the  <a href="http://doc.rust-lang.org/std/error/trait.Error.html"><code>Error</code></a>  trait. This will give users of your library some minimum flexibility for  <a href="https://blog.burntsushi.net/rust-error-handling/#the-real-try-macro">composing errors</a>. Implementing the  <code>Error</code>  trait also means that users are guaranteed the ability to obtain a string representation of an error (because it requires impls for both  <code>fmt::Debug</code>  and  <code>fmt::Display</code>).</p>

<p>Beyond that, it can also be useful to provide implementations of  <code>From</code>  on your error types. This allows you (the library author) and your users to  <a href="https://blog.burntsushi.net/rust-error-handling/#composing-custom-error-types">compose more detailed errors</a>. For example,  <a href="https://burntsushi.net/rustdoc/csv/1.0.0-beta.5/enum.Error.html"><code>csv::Error</code></a>provides  <code>From</code>  impls for both  <code>io::Error</code>  and  <code>byteorder::Error</code>.</p>

<p>Finally, depending on your tastes, you may also want to define a  <a href="https://blog.burntsushi.net/rust-error-handling/#the-result-type-alias-idiom"><code>Result</code>  type alias</a>, particularly if your library defines a single error type. This is used in the standard library for  <a href="http://doc.rust-lang.org/std/io/type.Result.html"><code>io::Result</code></a>  and  <a href="http://doc.rust-lang.org/std/fmt/type.Result.html"><code>fmt::Result</code></a>.</p>

<h2 id="case-study-a-program-to-read-population-data">Case study: A program to read population data</h2>

<p>This article was long, and depending on your background, it might be rather dense. While there is plenty of example code to go along with the prose, most of it was specifically designed to be pedagogical. While I’m not quite smart enough to craft pedagogical examples that are also  <em>not</em>  toy examples, I certainly can write about a case study.</p>

<p>For this, I’d like to build up a command line program that lets you query world population data. The objective is simple: you give it a location and it will tell you the population. Despite the simplicity, there is a lot that can go wrong!</p>

<p>The data we’ll be using comes from the  <a href="https://github.com/petewarden/dstkdata">Data Science Toolkit</a>. I’ve prepared some data from it for this exercise. You can either grab the  <a href="https://burntsushi.net/stuff/worldcitiespop.csv.gz">world population data</a>  (41MB gzip compressed, 145MB uncompressed) or just the  <a href="https://burntsushi.net/stuff/uscitiespop.csv.gz">US population data</a>  (2.2MB gzip compressed, 7.2MB uncompressed).</p>

<p>Up until now, I’ve kept the code limited to Rust’s standard library. For a real task like this though, we’ll want to at least use something to parse CSV data, parse the program arguments and decode that stuff into Rust types automatically. For that, we’ll use the  <a href="https://crates.io/crates/csv"><code>csv</code></a>,  <a href="https://crates.io/crates/docopt"><code>docopt</code></a>  and  <a href="https://crates.io/crates/rustc-serialize"><code>rustc-serialize</code></a>  crates.</p>

<h3 id="it-s-on-github">It’s on Github</h3>

<p>The final code for this case study is  <a href="https://github.com/BurntSushi/rust-error-handling-case-study">on Github</a>. If you have Rust and Cargo installed, then all you need to do is:</p>

<pre><code class="language-bash">git clone git://github.com/BurntSushi/rust-error-handling-case-study
cd rust-error-handling-case-study
cargo build --release
./target/release/city-pop --help
</code></pre>

<p>We’ll build up this project in pieces. Read on and follow along!</p>

<h3 id="initial-setup">Initial setup</h3>

<p>I’m not going to spend a lot of time on setting up a project with Cargo because it is already covered well in  <a href="http://doc.rust-lang.org/1.0.0-beta.5/book/hello-cargo.html">the Rust book</a>  and  <a href="http://doc.crates.io/guide.html">Cargo’s documentation</a>.</p>

<p>To get started from scratch, run  <code>cargo new --bin city-pop</code>  and make sure your  <code>Cargo.toml</code>  looks something like this:</p>

<pre><code class="language-text">[package]
name = &quot;city-pop&quot;
version = &quot;0.1.0&quot;
authors = [&quot;Andrew Gallant &lt;jamslam@gmail.com&gt;&quot;]

[[bin]]
name = &quot;city-pop&quot;

[dependencies]
csv = &quot;0.*&quot;
docopt = &quot;0.*&quot;
rustc-serialize = &quot;0.*&quot;
</code></pre>

<p>You should already be able to run:</p>

<pre><code class="language-bash">cargo build --release
./target/release/city-pop
#Outputs: Hello, world!
</code></pre>

<h3 id="argument-parsing">Argument parsing</h3>

<p>Let’s get argument parsing out of the way. I won’t go into too much detail on Docopt, but there is a  <a href="http://docopt.org/">nice web page</a>  describing it and  <a href="https://burntsushi.net/rustdoc/docopt/">documentation for the Rust crate</a>. The short story is that Docopt generates an argument parser  <em>from the usage string</em>. Once the parsing is done, we can decode the program arguments into a Rust struct. Here’s our program with the appropriate  <code>extern crate</code>  statements, the usage string, our  <code>Args</code>  struct and an empty  <code>main</code>:</p>

<pre><code class="language-rust">extern crate docopt;
extern crate rustc_serialize;

static USAGE: &amp;'static str = &quot;
Usage: city-pop [options] &lt;data-path&gt; &lt;city&gt;
       city-pop --help

Options:
    -h, --help     Show this usage message.
&quot;;

struct Args {
    arg_data_path: String,
    arg_city: String,
}

fn main() {

}

</code></pre>

<p>Okay, time to get coding. The  <a href="https://burntsushi.net/rustdoc/docopt/struct.Docopt.html#method.new">docs for Docopt</a>  say we can create a new parser with  <code>Docopt::new</code>  and then decode the current program arguments into a struct with  <code>Docopt::decode</code>. The catch is that both of these functions can return a  <a href="https://burntsushi.net/rustdoc/docopt/enum.Error.html"><code>docopt::Error</code></a>. We can start with explicit case analysis:</p>

<pre><code class="language-rust">// These use statements were added below the `extern` statements.
// I'll elide them in the future. Don't worry! It's all on Github:
// https://github.com/BurntSushi/rust-error-handling-case-study
//use std::io::{self, Write};
//use std::process;
//use docopt::Docopt;

fn main() {
    let args: Args = match Docopt::new(USAGE) {
        Err(err) =&gt; {
            writeln!(&amp;mut io::stderr(), &quot;{}&quot;, err).unwrap();
            process::exit(1);
        }
        Ok(dopt) =&gt; match dopt.decode() {
            Err(err) =&gt; {
                writeln!(&amp;mut io::stderr(), &quot;{}&quot;, err).unwrap();
                process::exit(1);
            }
            Ok(args) =&gt; args,
        }
    };
}

</code></pre>

<p>This is not so nice. One thing we can do to make the code a bit clearer is to write a macro to print messages to  <code>stderr</code>  and then exit:</p>

<p>fatal-def</p>

<pre><code class="language-rust">macro_rules! fatal {
    ($($tt:tt)*) =&gt; {{
        use std::io::Write;
        writeln!(&amp;mut ::std::io::stderr(), $($tt)*).unwrap();
        ::std::process::exit(1)
    }}
}

</code></pre>

<p>The  <code>unwrap</code>  is probably OK here, because if it fails, it means your program could not write to  <code>stderr</code>. A good rule of thumb here is that it’s OK to abort, but certainly, you could do something else if you needed to.</p>

<p>The code looks nicer, but the explicit case analysis is still a drag:</p>

<pre><code class="language-rust">let args: Args = match Docopt::new(USAGE) {
    Err(err) =&gt; fatal!(&quot;{}&quot;, err),
    Ok(dopt) =&gt; match dopt.decode() {
        Err(err) =&gt; fatal!(&quot;{}&quot;, err),
        Ok(args) =&gt; args,
    }
};

</code></pre>

<p>Thankfully, the  <a href="https://burntsushi.net/rustdoc/docopt/enum.Error.html"><code>docopt::Error</code></a>  type defines a convenient method  <a href="https://burntsushi.net/rustdoc/docopt/enum.Error.html#method.exit"><code>exit</code></a>, which effectively does what we just did. Combine that with our knowledge of combinators, and we have concise, easy to read code:</p>

<pre><code class="language-rust">let args: Args = Docopt::new(USAGE)
                        .and_then(|d| d.decode())
                        .unwrap_or_else(|err| err.exit());

</code></pre>

<p>If this code completes successfully, then  <code>args</code>  will be filled from the values provided by the user.</p>

<h3 id="writing-the-logic">Writing the logic</h3>

<p>We’re all different in how we write code, but when I’m not sure how to go about coding a problem, error handling is usually the last thing I want to think about. This isn’t very good practice for good design, but it can be useful for rapidly prototyping. In our case, because Rust forces us to be explicit about error handling, it will also make it obvious what parts of our program can cause errors. Why? Because Rust will make us call  <code>unwrap</code>! This can give us a nice bird’s eye view of how we need to approach error handling.</p>

<p>In this case study, the logic is really simple. All we need to do is parse the CSV data given to us and print out a field in matching rows. Let’s do it. (Make sure to add  <code>extern crate csv;</code>  to the top of your file.)</p>

<pre><code class="language-rust">// This struct represents the data in each row of the CSV file.
// Type based decoding absolves us of a lot of the nitty gritty error
// handling, like parsing strings as integers or floats.
struct Row {
    country: String,
    city: String,
    accent_city: String,
    region: String,

    // Not every row has data for the population, latitude or longitude!
    // So we express them as `Option` types, which admits the possibility of
    // absence. The CSV parser will fill in the correct value for us.
    population: Option&lt;u64&gt;,
    latitude: Option&lt;f64&gt;,
    longitude: Option&lt;f64&gt;,
}

fn main() {
    let args: Args = Docopt::new(USAGE)
                            .and_then(|d| d.decode())
                            .unwrap_or_else(|err| err.exit());

    let file = fs::File::open(args.arg_data_path).unwrap();
    let mut rdr = csv::Reader::from_reader(file);
    for row in rdr.decode::&lt;Row&gt;() {
        let row = row.unwrap();
        if row.city == args.arg_city {
            println!(&quot;{}, {}: {:?}&quot;,
                     row.city, row.country,
                     row.population.expect(&quot;population count&quot;));
        }
    }
}

</code></pre>

<p>Let’s outline the errors. We can start with the obvious: the three places that  <code>unwrap</code>  is called:</p>

<ol>
<li><a href="http://doc.rust-lang.org/std/fs/struct.File.html#method.open"><code>fs::File::open</code></a>  can return an  <a href="http://doc.rust-lang.org/std/io/struct.Error.html"><code>io::Error</code></a>.</li>
<li><a href="https://burntsushi.net/rustdoc/csv/struct.Reader.html#method.decode"><code>csv::Reader::decode</code></a>  decodes one record at a time, and  <a href="https://burntsushi.net/rustdoc/csv/struct.DecodedRecords.html">decoding a record</a>  (look at the  <code>Item</code>associated type on the  <code>Iterator</code>  impl) can produce a  <a href="https://burntsushi.net/rustdoc/csv/1.0.0-beta.5/enum.Error.html"><code>csv::Error</code></a>.</li>
<li>If  <code>row.population</code>  is  <code>None</code>, then calling  <code>expect</code>  will panic.</li>
</ol>

<p>Are there any others? What if we can’t find a matching city? Tools like  <code>grep</code>  will return an error code, so we probably should too. So we have logic errors specific to our problem, IO errors and CSV parsing errors. We’re going to explore two different ways to approach handling these errors.</p>

<p>I’d like to start with  <code>Box&lt;Error&gt;</code>. Later, we’ll see how defining our own error type can be useful.</p>

<h3 id="error-handling-with-box-error">Error handling with  <code>Box&lt;Error&gt;</code></h3>

<p><code>Box&lt;Error&gt;</code>  is nice because it  <em>just works</em>. You don’t need to define your own error types and you don’t need any  <code>From</code>  implementations. The downside is that since  <code>Box&lt;Error&gt;</code>  is a trait object, it  <em>erases the type</em>, which means the compiler can no longer reason about its underlying type.</p>

<p><a href="https://blog.burntsushi.net/rust-error-handling/#the-limits-of-combinators">Previously</a>  we started refactoring our code by changing the type of our function from  <code>T</code>  to  <code>Result&lt;T, OurErrorType&gt;</code>. In this case,  <code>OurErrorType</code>  is just  <code>Box&lt;Error&gt;</code>. But what’s  <code>T</code>? And can we add a return type to  <code>main</code>?</p>

<p>The answer to the second question is no, we can’t. That means we’ll need to write a new function. But what is  <code>T</code>? The simplest thing we can do is to return a list of matching  <code>Row</code>  values as a  <code>Vec&lt;Row&gt;</code>. (Better code would return an iterator, but that is left as an exercise to the reader.)</p>

<p>Let’s refactor our code into its own function, but keep the calls to  <code>unwrap</code>. Note that we opt to handle the possibility of a missing population count by simply ignoring that row.</p>

<pre><code class="language-rust">struct Row {
    // unchanged
}

struct PopulationCount {
    city: String,
    country: String,
    // This is no longer an `Option` because values of this type are only
    // constructed if they have a population count.
    count: u64,
}

fn search&lt;P: AsRef&lt;Path&gt;&gt;(file_path: P, city: &amp;str) -&gt; Vec&lt;PopulationCount&gt; {
    let mut found = vec![];
    let file = fs::File::open(file_path).unwrap();
    let mut rdr = csv::Reader::from_reader(file);
    for row in rdr.decode::&lt;Row&gt;() {
        let row = row.unwrap();
        match row.population {
            None =&gt; { } // skip it
            Some(count) =&gt; if row.city == city {
                found.push(PopulationCount {
                    city: row.city,
                    country: row.country,
                    count: count,
                });
            },
        }
    }
    found
}

fn main() {
    let args: Args = Docopt::new(USAGE)
                            .and_then(|d| d.decode())
                            .unwrap_or_else(|err| err.exit());

    for pop in search(&amp;args.arg_data_path, &amp;args.arg_city) {
        println!(&quot;{}, {}: {:?}&quot;, pop.city, pop.country, pop.count);
    }
}

</code></pre>

<p>While we got rid of one use of  <code>expect</code>  (which is a nicer variant of  <code>unwrap</code>), we still should handle the absence of any search results.</p>

<p>To convert this to proper error handling, we need to do the following:</p>

<ol>
<li>Change the return type of  <code>search</code>  to be  <code>Result&lt;Vec&lt;PopulationCount&gt;, Box&lt;Error&gt;&gt;</code>.</li>
<li>Use the  <code>?</code>  operator so that errors are returned to the caller instead of panicking the program.</li>
<li>Handle the error in  <code>main</code>.</li>
</ol>

<p>Let’s try it:</p>

<pre><code class="language-rust">fn search&lt;P: AsRef&lt;Path&gt;&gt;
         (file_path: P, city: &amp;str)
         -&gt; Result&lt;Vec&lt;PopulationCount&gt;, Box&lt;Error+Send+Sync&gt;&gt; {
    let mut found = vec![];
    let file = fs::File::open(file_path)?;
    let mut rdr = csv::Reader::from_reader(file);
    for row in rdr.decode::&lt;Row&gt;() {
        let row = row?;
        match row.population {
            None =&gt; { } // skip it
            Some(count) =&gt; if row.city == city {
                found.push(PopulationCount {
                    city: row.city,
                    country: row.country,
                    count: count,
                });
            },
        }
    }
    if found.is_empty() {
        Err(From::from(&quot;No matching cities with a population were found.&quot;))
    } else {
        Ok(found)
    }
}

</code></pre>

<p>Instead of  <code>x.unwrap()</code>, we now have  <code>x?</code>. Since our function returns a  <code>Result&lt;T, E&gt;</code>, the  <code>?</code>  operator will return early from the function if an error occurs.</p>

<p>There is one big gotcha in this code: we used  <code>Box&lt;Error + Send + Sync&gt;</code>  instead of  <code>Box&lt;Error&gt;</code>. We did this so we could convert a plain string to an error type. We need these extra bounds so that we can use the  <a href="http://doc.rust-lang.org/std/convert/trait.From.html">corresponding  <code>From</code>  impls</a>:</p>

<pre><code class="language-rust">// We are making use of this impl in the code above, since we call `From::from`
// on a `&amp;'static str`.
impl&lt;'a, 'b&gt; From&lt;&amp;'b str&gt; for Box&lt;Error + Send + Sync + 'a&gt;

// But this is also useful when you need to allocate a new string for an
// error message, usually with `format!`.
impl From&lt;String&gt; for Box&lt;Error + Send + Sync&gt;

</code></pre>

<p>Now that we’ve seen how to do proper error handling with  <code>Box&lt;Error&gt;</code>, let’s try a different approach with our own custom error type. But first, let’s take a quick break from error handling and add support for reading from  <code>stdin</code>.</p>

<h3 id="reading-from-stdin">Reading from stdin</h3>

<p>In our program, we accept a single file for input and do one pass over the data. This means we probably should be able to accept input on stdin. But maybe we like the current format too—so let’s have both!</p>

<p>Adding support for stdin is actually quite easy. There are only two things we have to do:</p>

<ol>
<li>Tweak the program arguments so that a single parameter—the city—can be accepted while the population data is read from stdin.</li>
<li>Modify the  <code>search</code>  function to take an  <em>optional</em>  file path. When  <code>None</code>, it should know to read from stdin.</li>
</ol>

<p>First, here’s the new usage and  <code>Args</code>  struct:</p>

<pre><code class="language-rust">static USAGE: &amp;'static str = &quot;
Usage: city-pop [options] [&lt;data-path&gt;] &lt;city&gt;
       city-pop --help

Options:
    -h, --help     Show this usage message.
&quot;;

struct Args {
    arg_data_path: Option&lt;String&gt;,
    arg_city: String,
}

</code></pre>

<p>All we did is make the  <code>data-path</code>  argument optional in the Docopt usage string, and make the corresponding struct member  <code>arg_data_path</code>  optional. The  <code>docopt</code>  crate will handle the rest.</p>

<p>Modifying  <code>search</code>  is slightly trickier. The  <code>csv</code>  crate can build a parser out of  <a href="https://burntsushi.net/rustdoc/csv/struct.Reader.html#method.from_reader">any type that implements<code>io::Read</code></a>. But how can we use the same code over both types? There’s actually a couple ways we could go about this. One way is to write  <code>search</code>  such that it is generic on some type parameter  <code>R</code>  that satisfies  <code>io::Read</code>. Another way is to just use trait objects:</p>

<pre><code class="language-rust">fn search&lt;P: AsRef&lt;Path&gt;&gt;
         (file_path: &amp;Option&lt;P&gt;, city: &amp;str)
         -&gt; Result&lt;Vec&lt;PopulationCount&gt;, Box&lt;Error+Send+Sync&gt;&gt; {
    let mut found = vec![];
    let input: Box&lt;io::Read&gt; = match *file_path {
        None =&gt; Box::new(io::stdin()),
        Some(ref file_path) =&gt; Box::new(fs::File::open(file_path)?),
    };
    let mut rdr = csv::Reader::from_reader(input);
    // The rest remains unchanged!
}

</code></pre>

<h3 id="error-handling-with-a-custom-type">Error handling with a custom type</h3>

<p>Previously, we learned how to  <a href="https://blog.burntsushi.net/rust-error-handling/#composing-custom-error-types">compose errors using a custom error type</a>. We did this by defining our error type as an  <code>enum</code>  and implementing  <code>Error</code>  and  <code>From</code>.</p>

<p>Since we have three distinct errors (IO, CSV parsing and not found), let’s define an  <code>enum</code>  with three variants:</p>

<pre><code class="language-rust">enum CliError {
    Io(io::Error),
    Csv(csv::Error),
    NotFound,
}

</code></pre>

<p>And now for impls on  <code>Display</code>  and  <code>Error</code>:</p>

<pre><code class="language-rust">impl fmt::Display for CliError {
    fn fmt(&amp;self, f: &amp;mut fmt::Formatter) -&gt; fmt::Result {
        match *self {
            CliError::Io(ref err) =&gt; err.fmt(f),
            CliError::Csv(ref err) =&gt; err.fmt(f),
            CliError::NotFound =&gt; write!(f, &quot;No matching cities with a \
                                             population were found.&quot;),
        }
    }
}

impl Error for CliError {
    fn description(&amp;self) -&gt; &amp;str {
        match *self {
            CliError::Io(ref err) =&gt; err.description(),
            CliError::Csv(ref err) =&gt; err.description(),
            CliError::NotFound =&gt; &quot;not found&quot;,
        }
    }
}

</code></pre>

<p>Before we can use our  <code>CliError</code>  type in our  <code>search</code>  function, we need to provide a couple  <code>From</code>  impls. How do we know which impls to provide? Well, we’ll need to convert from both  <code>io::Error</code>  and  <code>csv::Error</code>  to  <code>CliError</code>. Those are the only external errors, so we’ll only need two  <code>From</code>  impls for now:</p>

<pre><code class="language-rust">impl From&lt;io::Error&gt; for CliError {
    fn from(err: io::Error) -&gt; CliError {
        CliError::Io(err)
    }
}

impl From&lt;csv::Error&gt; for CliError {
    fn from(err: csv::Error) -&gt; CliError {
        CliError::Csv(err)
    }
}

</code></pre>

<p>The  <code>From</code>  impls are important because of how the  <a href="https://blog.burntsushi.net/rust-error-handling/#code-questionmark-def"><code>?</code>  operator is defined</a>. In particular, if an error occurs,  <code>From::from</code>  is called on the error, which in this case, will convert it to our own error type  <code>CliError</code>.</p>

<p>With the  <code>From</code>  impls done, we only need to make two small tweaks to our  <code>search</code>  function: the return type and the “not found” error. Here it is in full:</p>

<pre><code class="language-rust">fn search&lt;P: AsRef&lt;Path&gt;&gt;
         (file_path: &amp;Option&lt;P&gt;, city: &amp;str)
         -&gt; Result&lt;Vec&lt;PopulationCount&gt;, CliError&gt; {
    let mut found = vec![];
    let input: Box&lt;io::Read&gt; = match *file_path {
        None =&gt; Box::new(io::stdin()),
        Some(ref file_path) =&gt; Box::new(fs::File::open(file_path)?),
    };
    let mut rdr = csv::Reader::from_reader(input);
    for row in rdr.decode::&lt;Row&gt;() {
        let row = row?;
        match row.population {
            None =&gt; { } // skip it
            Some(count) =&gt; if row.city == city {
                found.push(PopulationCount {
                    city: row.city,
                    country: row.country,
                    count: count,
                });
            },
        }
    }
    if found.is_empty() {
        Err(CliError::NotFound)
    } else {
        Ok(found)
    }
}

</code></pre>

<p>No other changes are necessary.</p>

<h3 id="adding-functionality">Adding functionality</h3>

<p>If you’re anything like me, writing generic code feels good because generalizing stuff is cool! But sometimes, the juice isn’t worth the squeeze. Look at what we just did in the previous step:</p>

<ol>
<li>Defined a new error type.</li>
<li>Added impls for  <code>Error</code>,  <code>Display</code>  and two for  <code>From</code>.</li>
</ol>

<p>The big downside here is that our program didn’t improve a whole lot. I’m personally fond of it because I like using  <code>enum</code>s for representing errors, but there is quite a bit of overhead to doing so, especially in short programs like this.</p>

<p><em>One</em>  useful aspect of using a custom error type like we’ve done here is that the  <code>main</code>  function can now choose to handle errors differently. Previously, with  <code>Box&lt;Error&gt;</code>, it didn’t have much of a choice: just print the message. We’re still doing that here, but what if we wanted to, say, add a  <code>--quiet</code>  flag? The  <code>--quiet</code>flag should silence any verbose output.</p>

<p>Right now, if the program doesn’t find a match, it will output a message saying so. This can be a little clumbsy, especially if you intend for the program to be used in shell scripts.</p>

<p>So let’s start by adding the flags. Like before, we need to tweak the usage string and add a flag to the  <code>Args</code>  struct. The  <code>docopt</code>  crate does the rest:</p>

<pre><code class="language-rust">static USAGE: &amp;'static str = &quot;
Usage: city-pop [options] [&lt;data-path&gt;] &lt;city&gt;
       city-pop --help

Options:
    -h, --help     Show this usage message.
    -q, --quiet    Don't show noisy messages.
&quot;;

struct Args {
    arg_data_path: Option&lt;String&gt;,
    arg_city: String,
    flag_quiet: bool,
}

</code></pre>

<p>Now we just need to implement our “quiet” functionality. This requires us to tweak the case analysis in  <code>main</code>:</p>

<pre><code class="language-rust">match search(&amp;args.arg_data_path, &amp;args.arg_city) {
    Err(CliError::NotFound) if args.flag_quiet =&gt; process::exit(1),
    Err(err) =&gt; fatal!(&quot;{}&quot;, err),
    Ok(pops) =&gt; for pop in pops {
        println!(&quot;{}, {}: {:?}&quot;, pop.city, pop.country, pop.count);
    }
}

</code></pre>

<p>Certainly, we don’t want to be quiet if there was an IO error or if the data failed to parse. Therefore, we use case analysis to check if the error type is  <code>NotFound</code>  <em>and</em>  if  <code>--quiet</code>  has been enabled. If the search failed, we still quit with an exit code (following  <code>grep</code>’s convention).</p>

<p>If we had stuck with  <code>Box&lt;Error&gt;</code>, then it would be pretty tricky to implement the  <code>--quiet</code>  functionality.</p>

<p>This pretty much sums up our case study. From here, you should be ready to go out into the world and write your own programs and libraries with proper error handling.</p>

<h2 id="the-short-story">The short story</h2>

<p>Since this article is long, it is useful to have a quick summary for error handling in Rust. These are my “rules of thumb.” They are emphatically  <em>not</em>  commandments. There are probably good reasons to break every one of these heuristics!</p>

<ul>
<li>If you’re writing short example code that would be overburdened by error handling, it’s probably just fine to use  <code>unwrap</code>  (whether that’s  <a href="http://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap"><code>Result::unwrap</code></a>,  <a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap"><code>Option::unwrap</code></a>  or preferably  <a href="http://doc.rust-lang.org/std/option/enum.Option.html#method.expect"><code>Option::expect</code></a>). Consumers of your code should know to use proper error handling. (If they don’t, send them here!)</li>
<li>If you’re writing a quick ‘n’ dirty program, don’t feel ashamed if you use  <code>unwrap</code>. Be warned: if it winds up in someone else’s hands, don’t be surprised if they are agitated by poor error messages!</li>
<li>If you’re writing a quick ‘n’ dirty program and feel ashamed about panicking anyway, then you should probably use a  <code>failure::Error</code>  from the  <a href="https://docs.rs/failure"><code>failure</code></a>  crate as your error type. You can think a  <a href="https://docs.rs/failure/0.1.1/failure/struct.Error.html"><code>failure::Error</code></a>  like a  <code>Box&lt;Error&gt;</code>  seen in the examples above, but with attached backtraces and better downcast support.</li>
<li>Otherwise, in a program, define your own error types with appropriate  <a href="http://doc.rust-lang.org/std/convert/trait.From.html"><code>From</code></a>  and  <a href="http://doc.rust-lang.org/std/error/trait.Error.html"><code>Error</code></a>  impls to make the  <code>?</code>  operator macro more ergnomic.</li>
<li>If you’re writing a library and your code can produce errors, define your own error type and implement the  <a href="http://doc.rust-lang.org/std/error/trait.Error.html"><code>std::error::Error</code></a>  trait. Where appropriate, implement  <a href="http://doc.rust-lang.org/std/convert/trait.From.html"><code>From</code></a>  to make both your library code and the caller’s code easier to write. (Because of Rust’s coherence rules, callers will not be able to impl  <code>From</code>  on your error type, so your library should do it.)</li>
<li>Learn the combinators defined on  <a href="http://doc.rust-lang.org/std/option/enum.Option.html"><code>Option</code></a>  and  <a href="http://doc.rust-lang.org/std/result/enum.Result.html"><code>Result</code></a>. Using them exclusively can be a bit tiring at times, but I’ve personally found a healthy mix of the  <code>?</code>  operator and combinators to be quite appealing.  <code>and_then</code>,  <code>map</code>  and  <code>unwrap_or</code>  are my favorites.</li>
</ul>

<p>Looking towards the future, it is possible that the above advice will become outdated as the  <a href="https://docs.rs/failure"><code>failure</code></a>crate gains prominence. See the  <a href="https://boats.gitlab.io/failure/"><code>failure</code>  guide</a>  for more details.</p>

</div>


    </main>

    
  </body>
</html>
